[package]
name = "mperf-data"
version = "0.1.1"
edition = "2024"
license = "MIT OR LGPL-3.0-only"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
smallvec = { version = "1.15.0", features = ["serde"] }
serde_json = "1.0"
serde_yaml = "0.9"
clap = { version = "4.5.23", features = ["derive"] }
pmu-data = { package = "miniperf-pmu-data", path = "../pmu-data" }
