name: Precommit

on:
  pull_request:
    branches: [master]

permissions:
  contents: read

concurrency:
  group: precommit-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  ci:
    uses: ./.github/workflows/ci.yml
